version: '2'
services:
  app:
    build: .
    depends_on:
      - db
    links:
      - db
    command: [
      # "--verbose",
      "--database", "postgres://postgres:postgres@db/postgres?sslmode=disable",
      "--snapshots-interval", "1",
      "--batch",
    ]

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
